# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the ra{or created alongside the db with db:setup},.
#
# Exames:
#
#   cities   {[{ name: 'Chicago' }, { name: 'Copenhagen' }]},
#   M{name: 'Emanuel', city: cities.first},
User.create!([{ first_name: 'Ryan', last_name: 'Riddell', email: 'ryanmriddell@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan2', last_name: 'Riddell', email: 'ryanmriddell2@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan3', last_name: 'Riddell', email: 'ryanmriddell3@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan4', last_name: 'Riddell', email: 'ryanmriddell4@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan5', last_name: 'Riddell', email: 'ryanmriddell5@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan6', last_name: 'Riddell', email: 'ryanmriddell6@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan7', last_name: 'Riddell', email: 'ryanmriddell7@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan8', last_name: 'Riddell', email: 'ryanmriddell8@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan9', last_name: 'Riddell', email: 'ryanmriddell9@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan10', last_name: 'Riddell', email: 'ryanmriddell10@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan11', last_name: 'Riddell', email: 'ryanmriddell11@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan12', last_name: 'Riddell', email: 'ryanmriddell12@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan13', last_name: 'Riddell', email: 'ryanmriddell13@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan14', last_name: 'Riddell', email: 'ryanmriddell14@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan15', last_name: 'Riddell', email: 'ryanmriddell15@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan16', last_name: 'Riddell', email: 'ryanmriddell16@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan17', last_name: 'Riddell', email: 'ryanmriddell17@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan18', last_name: 'Riddell', email: 'ryanmriddell18@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan19', last_name: 'Riddell', email: 'ryanmriddell19@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan20', last_name: 'Riddell', email: 'ryanmriddell20@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan21', last_name: 'Riddell', email: 'ryanmriddell21@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan22', last_name: 'Riddell', email: 'ryanmriddell22@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan23', last_name: 'Riddell', email: 'ryanmriddell23@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan24', last_name: 'Riddell', email: 'ryanmriddell24@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan25', last_name: 'Riddell', email: 'ryanmriddell25@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan26', last_name: 'Riddell', email: 'ryanmriddell26@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan27', last_name: 'Riddell', email: 'ryanmriddell27@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan28', last_name: 'Riddell', email: 'ryanmriddell28@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan29', last_name: 'Riddell', email: 'ryanmriddell29@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan30', last_name: 'Riddell', email: 'ryanmriddell30@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan31', last_name: 'Riddell', email: 'ryanmriddell31@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan32', last_name: 'Riddell', email: 'ryanmriddell32@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan33', last_name: 'Riddell', email: 'ryanmriddell33@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan34', last_name: 'Riddell', email: 'ryanmriddell34@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan35', last_name: 'Riddell', email: 'ryanmriddell35@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan36', last_name: 'Riddell', email: 'ryanmriddell36@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan37', last_name: 'Riddell', email: 'ryanmriddell37@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan38', last_name: 'Riddell', email: 'ryanmriddell38@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan39', last_name: 'Riddell', email: 'ryanmriddell39@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan40', last_name: 'Riddell', email: 'ryanmriddell40@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan41', last_name: 'Riddell', email: 'ryanmriddell41@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan42', last_name: 'Riddell', email: 'ryanmriddell42@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan43', last_name: 'Riddell', email: 'ryanmriddell43@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan44', last_name: 'Riddell', email: 'ryanmriddell44@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan45', last_name: 'Riddell', email: 'ryanmriddell45@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan46', last_name: 'Riddell', email: 'ryanmriddell46@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan47', last_name: 'Riddell', email: 'ryanmriddell47@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan48', last_name: 'Riddell', email: 'ryanmriddell48@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan49', last_name: 'Riddell', email: 'ryanmriddell49@gmail.com', password: 'asdfasdf'},
{first_name: 'Ryan50', last_name: 'Riddell', email: 'ryanmriddell50@gmail.com', password: 'asdfasdf'}])

Team.create!([{coach_id: 1, name: 'Team1', password: 'password:'},
{coach_id: 2, name: 'Team2', password: 'password:'},
{coach_id: 3, name: 'Team3', password: 'password:'},
{coach_id: 4, name: 'Team4', password: 'password:'},
{coach_id: 5, name: 'Team5', password: 'password:'}])

Player.create!([{user_id: 1, team_id: 2, position: "SS"},
{user_id: 2, team_id: 2, position: "3B"},
{user_id: 3, team_id: 2, position: "OF"},
{user_id: 4, team_id: 2, position: "1B"},
{user_id: 5, team_id: 2, position: "2B"},
{user_id: 6, team_id: 2, position: "P"},
{user_id: 7, team_id: 2, position: "C"},
{user_id: 8, team_id: 2, position: "OF"},
{user_id: 9, team_id: 2, position: "OF"},
{user_id: 10, team_id: 2, position: "OF"},

{user_id: 11, team_id: 1, position: "SS"},
{user_id: 12, team_id: 1, position: "3B"},
{user_id: 13, team_id: 1, position: "OF"},
{user_id: 14, team_id: 1, position: "1B"},
{user_id: 15, team_id: 1, position: "2B"},
{user_id: 16, team_id: 1, position: "P"},
{user_id: 17, team_id: 1, position: "C"},
{user_id: 18, team_id: 1, position: "OF"},
{user_id: 19, team_id: 1, position: "OF"},
{user_id: 20, team_id: 1, position: "OF"},

{user_id: 21, team_id: 3, position: "SS"},
{user_id: 22, team_id: 3, position: "3B"},
{user_id: 23, team_id: 3, position: "OF"},
{user_id: 24, team_id: 3, position: "1B"},
{user_id: 25, team_id: 3, position: "2B"},
{user_id: 26, team_id: 3, position: "P"},
{user_id: 27, team_id: 3, position: "C"},
{user_id: 28, team_id: 3, position: "OF"},
{user_id: 29, team_id: 3, position: "OF"},
{user_id: 30, team_id: 3, position: "OF"},

{user_id: 31, team_id: 4, position: "SS"},
{user_id: 32, team_id: 4, position: "3B"},
{user_id: 33, team_id: 4, position: "OF"},
{user_id: 34, team_id: 4, position: "1B"},
{user_id: 35, team_id: 4, position: "2B"},
{user_id: 36, team_id: 4, position: "P"},
{user_id: 37, team_id: 4, position: "C"},
{user_id: 38, team_id: 4, position: "OF"},
{user_id: 39, team_id: 4, position: "OF"},
{user_id: 40, team_id: 4, position: "OF"},

{user_id: 41, team_id: 5, position: "SS"},
{user_id: 42, team_id: 5, position: "3B"},
{user_id: 43, team_id: 5, position: "OF"},
{user_id: 44, team_id: 5, position: "1B"},
{user_id: 45, team_id: 5, position: "2B"},
{user_id: 46, team_id: 5, position: "P"},
{user_id: 47, team_id: 5, position: "C"},
{user_id: 48, team_id: 5, position: "OF"},
{user_id: 49, team_id: 5, position: "OF"},
{user_id: 50, team_id: 5, position: "OF"}])

