User.create!([{
first_name: 'Ryan', 
last_name:'Riddell', 
email:'ryanmriddell@gmail.com', 
password:'asdfasdf'},
{first_name: 'Cob', 
last_name:'Cheson', 
email:'ccheson1@eventbrite.com', 
password:'IfjwoiejqWL6iPCboh'},
{first_name: 'Odille', 
last_name:'Wasielewicz', 
email:'owasielewicz2@sourceforge.net', 
password:'AfjwoiejFgpJg'},
{first_name: 'Laurent', 
last_name:'Strond', 
email:'lstrond3@exblog.jp', 
password:'kfjwoiejcaMXXK'},
{first_name: 'Maryl', 
last_name:'Ferenczi', 
email:'mferenczi4@diigo.com', 
password:'kfjwoiejMeg1HePE'},
{first_name: 'Eula', 
last_name:'Bewley', 
email:'ebewley5@globo.com', 
password:'7fjwoiejxfcKhQ'},
{first_name: 'Lina', 
last_name:'Caruth', 
email:'lcaruth6@twitpic.com', 
password:'cfjwoiejK3eno2vmyQ'},
{first_name: 'Gonzalo', 
last_name:'Shaxby', 
email:'gshaxby7@instagram.com', 
password:'jfjwoiejn0jiL5GT9qF'},
{first_name: 'Kendrick', 
last_name:'Di Roberto', 
email:'kdiroberto8@spotify.com', 
password:'efjwoiejZI3O7r'},
{first_name:  'Leanora', 
last_name: 'Blakden', 
email: 'lblakden9@bloomberg.com', 
password: 'fjwoieju80adyiTsYi3'},
{first_name: 'Darlene', 
last_name: 'Demare', 
email: 'ddemarea@artisteer.com', 
password: 'fjwoiejAudneZ8M1r'},
{first_name: 'Hew', 
last_name: 'Hallatt', 
email: 'hhallattb@mayoclinic.com', 
password: 'fjwoiejrJ6ZNU1'},
{first_name: 'Irving', 
last_name: 'Eagan', 
email: 'ieaganc@sun.com', 
password: 'fjwoiejZo7kNGu'},
{first_name: 'Corney', 
last_name: 'Plowes', 
email: 'cplowesd@businesswire.com', 
password: 'fjwoiejFvFOmooe'},
{first_name: 'Latrena', 
last_name: 'Lewis', 
email: 'llewise@state.tx.us', 
password: 'fjwoiejAoTunol5g9'},
{first_name: 'Flory', 
last_name: 'Isgate', 
email: 'fisgatef@huffingtonpost.com', 
password: 'fjwoiej4g5BSLErcjhY'},
{first_name: 'Tully', 
last_name: 'Flade', 
email: 'tfladeg@bloglovin.com', 
password: 'fjwoiejsY8ls6XTfy'},
{first_name: 'Livvy', 
last_name: 'Blemings', 
email: 'lblemingsh@dmoz.org', 
password: 'fjwoiejD5g5Z57H1iK'},
{first_name: 'Modestine', 
last_name: 'Skottle', 
email: 'mskottlei@cbslocal.com', 
password: 'fjwoiejKNULNI3pd'},
{first_name: 'Avictor', 
last_name: 'Biggar', 
email: 'abiggarj@si.edu', 
password: 'fjwoiej91qToXVhZ'},
{first_name: 'Gerry', 
last_name: 'Stappard', 
email: 'gstappardk@weibo.com', 
password: 'fjwoiejZ5foEaNxJXO'},
{first_name: 'Isidro', 
last_name: 'Halt', 
email: 'ihaltl@shinystat.com', 
password: 'fjwoiejuU6Tyr'},
{first_name: 'Maxy', 
last_name: 'Flaxman', 
email: 'mflaxmanm@timesonline.co.uk', 
password: 'fjwoiejQPqmIcaN5'},
{first_name: 'Rebecca', 
last_name: 'Crosher', 
email: 'rcroshern@time.com', 
password: 'fjwoiejHrohDSYNG'},
{first_name: 'Care', 
last_name: 'Box', 
email: 'cboxo@amazon.de', 
password: 'fjwoiejuc1erVi3SnP'},
{first_name: 'Colly', 
last_name: 'Migheli', 
email: 'cmighelip@about.com', 
password: 'fjwoiejUzpJSGZMiLTg'},
{first_name: 'Kari', 
last_name: 'Liversage', 
email: 'kliversageq@un.org', 
password: 'fjwoiejR1ZT9hQr6KR'},
{first_name: 'Anderea', 
last_name: 'Reinhard', 
email: 'areinhardr@aol.com', 
password: 'fjwoiejqnZauqsi'},
{first_name: 'Rebeca', 
last_name: 'Pervoe', 
email: 'rpervoes@barnesandnoble.com', 
password: 'fjwoiej2uPrhU0uOz'},
{first_name: 'Sidney', 
last_name: 'Suddell', 
email: 'ssuddellt@mysql.com', 
password: 'fjwoiej1llVmL'},
{first_name: 'Kristi', 
last_name: 'Vaillant', 
email: 'kvaillantu@senate.gov', 
password: 'fjwoiejK6nxJXgD887u'},
{first_name: 'Brent', 
last_name: 'Boshier', 
email: 'bboshierv@columbia.edu', 
password: 'fjwoiejR5G2HvTLE'},
{first_name: 'Josey', 
last_name: 'Ellington', 
email: 'jellingtonw@yellowbook.com', 
password: 'fjwoiejYI9Z5XI'},
{first_name: 'Jacqui', 
last_name: 'Layus', 
email: 'jlayusx@google.de', 
password: 'fjwoiejougTbb'},
{first_name: 'Jamaal', 
last_name: 'Burdis', 
email: 'jburdisy@tmall.com', 
password: 'fjwoiejZFq4mfXgnhE'},
{first_name: 'Ephrayim', 
last_name: 'Robion', 
email: 'erobionz@wp.com', 
password: 'fjwoiejcp1jd697O9j0'},
{first_name: 'Levi', 
last_name: 'Yakovliv', 
email: 'lyakovliv10@blogtalkradio.com', 
password: 'fjwoiejxGZ7Z5rzbf'},
{first_name: 'Freida', 
last_name: 'Girardetti', 
email: 'fgirardetti11@google.nl', 
password: 'fjwoiejfFP0Mfx'},
{first_name: 'Denver', 
last_name: 'Fakeley', 
email: 'dfakeley12@123-reg.co.uk', 
password: 'fjwoiejLd0xSFXBsr'},
{first_name: 'Dexter', 
last_name: 'Thorwarth', 
email: 'dthorwarth13@twitpic.com', 
password: 'fjwoiejT7rBrRK'},
{first_name: 'Harvey', 
last_name: 'Foote', 
email: 'hfoote14@about.com', 
password: 'fjwoiejKUU8aSD'},
{first_name: 'Heath', 
last_name: 'Lampe', 
email: 'hlampe15@chicagotribune.com', 
password: 'fjwoiejlA7lrVpH4puW'},
{first_name: 'Juanita', 
last_name: 'Urling', 
email: 'jurling16@cdbaby.com', 
password: 'fjwoiejE2ly50vy1oSp'},
{first_name: 'Gifford', 
last_name: 'McQuaide', 
email: 'gmcquaide17@flavors.me', 
password: 'fjwoiejHayWTH6jMWxa'},
{first_name: 'Marijn', 
last_name: 'Straneo', 
email: 'mstraneo18@spotify.com', 
password: 'fjwoiejFszZzVba'},
{first_name: 'Wendall', 
last_name: 'Peake', 
email: 'wpeake19@patch.com', 
password: 'fjwoiej9wPzkY'},
{first_name: 'Zared', 
last_name: 'Rickerd', 
email: 'zrickerd1a@vimeo.com', 
password: 'fjwoiejpAA1ckY6nck'},
{first_name: 'Xylia', 
last_name: 'Piniur', 
email: 'xpiniur1b@tiny.cc', 
password: 'fjwoiejyflVTUr'},
{first_name: 'Maurita', 
last_name: 'Ianelli', 
email: 'mianelli1c@ocn.ne.jp', 
password: 'fjwoiejSb9j1BWrGdh'},
{first_name: 'Olivette', 
last_name: 'Anniwell', 
email: 'oanniwell1d@mayoclinic.com', 
password: 'fjwoiejY0ryRkqN'},
{first_name: 'Shelly', 
last_name: 'Seston', 
email: 'sseston1e@themeforest.net', 
password: 'fjwoiej4upELYLpj697'},
{first_name: 'Linnie', 
last_name: 'Carbin', 
email: 'lcarbin1f@amazonaws.com', 
password: 'fjwoiej0toPtdLOq'},
{first_name: 'Babbie', 
last_name: 'Carragher', 
email: 'bcarragher1g@engadget.com', 
password: 'fjwoiejEQJrOESdok'},
{first_name: 'Robenia', 
last_name: 'Rowena', 
email: 'rrowena1h@vimeo.com', 
password: 'fjwoiejsrsSZTCR'},
{first_name: 'Massimiliano', 
last_name: 'Canet', 
email: 'mcanet1i@usgs.gov', 
password: 'fjwoiejkLgTORXUF'},
{first_name: 'Syman', 
last_name: 'McAvey', 
email: 'smcavey1j@wp.com', 
password: 'fjwoiejJWo2qiRar'},
{first_name: 'Der', 
last_name: 'Mayo', 
email: 'dmayo1k@stanford.edu', 
password: 'fjwoiejDFTKtABr'},
{first_name: 'Modestia', 
last_name: 'Trahearn', 
email: 'mtrahearn1l@buzzfeed.com', 
password: 'fjwoiejvd8y7UKn'},
{first_name: 'Marquita', 
last_name: 'Jessen', 
email: 'mjessen1m@goo.ne.jp', 
password: 'fjwoiejvhdCJvrwcbK'},
{first_name: 'Adria', 
last_name: 'Jobling', 
email: 'ajobling1n@mayoclinic.com', 
password: 'fjwoiejfiBpEqToW'},
{first_name: 'Kelly', 
last_name: 'Ivashov', 
email: 'kivashov1o@google.com.hk', 
password: 'fjwoiejXLKyUNxqazw'},
{first_name: 'Silas', 
last_name: 'Sciacovelli', 
email: 'ssciacovelli1p@mozilla.org', 
password: 'fjwoiejfEaAMbTS'},
{first_name: 'Erminie', 
last_name: 'Foresight', 
email: 'eforesight1q@google.ca', 
password: 'fjwoiejZBJNGE3C'},
{first_name: 'Cherilyn', 
last_name: 'Cheers', 
email: 'ccheers1r@bandcamp.com', 
password: 'fjwoiejbpHnqPDnEZB'},
{first_name: 'Ilysa', 
last_name: 'Wilmot', 
email: 'iwilmot1s@shutterfly.com', 
password: 'fjwoiejKir4fEhR'},
{first_name: 'Bentlee', 
last_name: 'Saddington', 
email: 'bsaddington1t@weebly.com', 
password: 'fjwoiejnEtJk1QcgjB'},
{first_name: 'Phineas', 
last_name: 'Burfitt', 
email: 'pburfitt1u@jalbum.net', 
password: 'fjwoiejLp8fVi'},
{first_name: 'Filmore', 
last_name: 'Fylan', 
email: 'ffylan1v@vkontakte.ru', 
password: 'fjwoiejEX59gA'},
{first_name: 'Kerstin', 
last_name: 'Dilawey', 
email: 'kdilawey1w@about.com', 
password: 'fjwoiej8l6BpjbYXFs'},
{first_name: 'Kipper', 
last_name: 'Ripping', 
email: 'kripping1x@shutterfly.com', 
password: 'fjwoiejG9NCUD6OMU'},
{first_name: 'Dani', 
last_name: 'Osman', 
email: 'dosman1y@ask.com', 
password: 'fjwoiejqJFNlf'},
{first_name: 'Octavia', 
last_name: 'Breens', 
email: 'obreens1z@vistaprint.com', 
password: 'fjwoiejumjBBhUJ0V'},
{first_name: 'Calhoun', 
last_name: 'Hembry', 
email: 'chembry20@wikimedia.org', 
password: 'fjwoiej7DVCWRkYm6D'},
{first_name: 'Grover', 
last_name: 'Humphrey', 
email: 'ghumphrey21@timesonline.co.uk', 
password: 'fjwoiejoAwNMa0Eg'},
{first_name: 'Cayla', 
last_name: 'Bellham', 
email: 'cbellham22@bravesites.com', 
password: 'fjwoiej8WEALQCgYU7X'},
{first_name: 'Wolfie', 
last_name: 'Blain', 
email: 'wblain23@ustream.tv', 
password: 'fjwoiejLualjbYzC'},
{first_name: 'Merle', 
last_name: 'Ricards', 
email: 'mricards24@nps.gov', 
password: 'fjwoiej8m9zv3IIW'},
{first_name: 'Ninnetta', 
last_name: 'Fleetham', 
email: 'nfleetham25@bizjournals.com', 
password: 'fjwoiejExwhl1xRQcJ'},
{first_name: 'Ezekiel', 
last_name: 'Trevett', 
email: 'etrevett26@barnesandnoble.com', 
password: 'fjwoiej8Gn2reDU2N'},
{first_name: 'Quint', 
last_name: 'Shefton', 
email: 'qshefton27@pinterest.com', 
password: 'fjwoiejWb7LsBF'},
{first_name: 'Port', 
last_name: 'Arzu', 
email: 'parzu28@cloudflare.com', 
password: 'fjwoiej3pPVHlKb'},
{first_name: 'Modestia', 
last_name: 'Canto', 
email: 'mcanto29@booking.com', 
password: 'fjwoiejuo0Yy9f4'},
{first_name: 'Kaleena', 
last_name: 'Royl', 
email: 'kroyl2a@google.ru', 
password: 'fjwoiejUr6m64p'},
{first_name: 'Matias', 
last_name: 'Oxbrough', 
email: 'moxbrough2b@wunderground.com', 
password: 'fjwoiejbmJHdyj'},
{first_name: 'Dermot', 
last_name: 'Goforth', 
email: 'dgoforth2c@bbc.co.uk', 
password: 'fjwoiejFBHvU3Ri'},
{first_name: 'Kimmy', 
last_name: 'Dawtrey', 
email: 'kdawtrey2d@biglobe.ne.jp', 
password: 'fjwoiejrl01LT'},
{first_name: 'Marlane', 
last_name: 'Melhuish', 
email: 'mmelhuish2e@lulu.com', 
password: 'fjwoiejZu8ZCSmVj3L'},
{first_name: 'Devan', 
last_name: 'Head', 
email: 'dhead2f@sfgate.com', 
password: 'fjwoiejaGBHbKJAH'},
{first_name: 'Michaeline', 
last_name: 'Pasmore', 
email: 'mpasmore2g@ucla.edu', 
password: 'fjwoiejBinZNi9uap'},
{first_name: 'Emory', 
last_name: 'Garth', 
email: 'egarth2h@elegantthemes.com', 
password: 'fjwoiejJAncFIXDG7'},
{first_name: 'Pancho', 
last_name: 'Shurrock', 
email: 'pshurrock2i@angelfire.com', 
password: 'fjwoiejUMSbRzSmsv6'},
{first_name: 'Timoteo', 
last_name: 'Grayshon', 
email: 'tgrayshon2j@jigsy.com', 
password: 'fjwoiejcYj76M'},
{first_name: 'Barton', 
last_name: 'O''Rodane', 
email: 'borodane2k@ihg.com', 
password: 'fjwoiejA4ZxJg9uhe'},
{first_name: 'Darcy', 
last_name: 'Ilem', 
email: 'dilem2l@prweb.com', 
password: 'fjwoiejdLFc9GUmQ0d0'},
{first_name: 'Bee', 
last_name: 'Dimnage', 
email: 'bdimnage2m@flickr.com', 
password: 'fjwoiej6708b5'},
{first_name: 'Wallie', 
last_name: 'Longhi', 
email: 'wlonghi2n@indiatimes.com', 
password: 'fjwoiejsYPteUecH'},
{first_name: 'Kipp', 
last_name: 'Lascell', 
email: 'klascell2o@lulu.com', 
password: 'fjwoiej5rRx7yv3R'},
{first_name: 'Gerick', 
last_name: 'Brady', 
email: 'gbrady2p@nydailynews.com', 
password: 'fjwoiejq40yvhsjU9'},
{first_name: 'Seth', 
last_name: 'Deal', 
email: 'sdeal2q@icio.us', 
password: 'fjwoiejYiLIhzUo'},
{first_name: 'Ardelis', 
last_name:'Traynor', 
email:'atraynor2r@e-recht24.de', 
password: 'fjwoiejntJJJkj6to'},
])
Team.create!([ { user_id: 1,
    name: 'Vandervort-DuBuque',
    password: 'tDDVZZxs'},
{ 
    user_id: 2, 
    name:'Hyatt, Zulauf and Nader',
    password: 'HHA6ZBmWVk7'},
{ 
    user_id: 3, 
    name:'Lowe, Swaniawski and Purdy',
    password: 'ipZ0bnQ'},
{ 
    user_id: 4, 
    name:'Tremblay-Borer',
    password: 'Y79ioD'},
{ 
    user_id: 5, 
    name:'Mertz-Wisoky',
    password: 'eZpkmuWdT2'},
{ 
    user_id: 6, 
    name:'Pouros and Sons',
    password: 'BG9Yvf'},
{ 
    user_id: 7, 
    name: 'O''Kon, Nitzsche and McDermott',
    password: 'vNjnyKe'},
{ 
    user_id: 8, 
    name: 'Wisozk-Zboncak',
    password: 'cOdX0n'},
{ 
    user_id: 9, 
    name: 'Wilderman and Sons',
    password: '7Q1wt0QccVy'},
{ 
    user_id: 10,
    name:  'Mante, Hagenes and Kessler',
    password:  'x4gywDp'},
{ 
    user_id: 11,
    name:  'Gislason and Sons',
    password:  'G2jfLr'},
{ 
    user_id: 12,
    name: 'Cummings-Crooks',
    password:  'Kgbt4gm5RRM'},
{ 
    user_id: 13,
    name: 'Connelly Inc',
    password:  'gwlNJ8D6t'},
{ 
    user_id: 14,
    name: 'Reichel, Medhurst and Fisher',
    password:  'nnJXj1nI3PCq'},
{ 
    user_id: 15,
    name: 'Hammes Inc',
    password:  '9yX0zphaI3'},
{ 
    user_id: 16,
    name: 'Weimann and Sons',
    password:  'yGSV9N8K'},
{ 
    user_id: 17,
    name: 'Emard-Weissnat',
    password:  'a9Nj9JitenZx'},
{ 
    user_id: 18,
    name: 'Hahn-Altenwerth',
    password:  'J2lLID'},
{ 
    user_id: 19,
    name: 'Herzog, Lebsack and Conn',
    password:  'M4luos8qCq'},
{ 
    user_id: 20,
    name: 'Lemke LLC',
    password:  '2ELpXKlt5t'}])